CREATE TABLE team (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    team_name TEXT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE users (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name TEXT NOT NULL,
    phone_number TEXT NOT NULL,
    team_id INT,
    role VARCHAR(255) NOT NULL DEFAULT 'user',
    FOREIGN KEY (team_id) REFERENCES team(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE user_tickets (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id INT,
    ticket_number TEXT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
