name: CI

on:
  push:
    branches: ["deploy"]
    paths-ignore:
      - "README.md"
      - "Dockerfile"
  pull_request:
    branches: ["deploy"]
    paths-ignore:
      - "README.md"
      - "Dockerfile"

env:
  CARGO_TERM_COLOR: always
  DATABASE_URL: ${{ vars.DATABASE_URL }}
  PORT: ${{ vars.PORT }}
  JWT_SECRET: ${{ vars.JWT_SECRET }}
  JWT_TTL_IN_MINUTES: 60

jobs:
  build-docker-img:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set environment variables in .env
        run: |
          echo "DATABASE_URL=$DATABASE_URL" >> .env
          echo "PORT=$PORT" >> .env
          echo "JWT_SECRET=$JWT_SECRET" >> .env
          echo "JWT_TTL_IN_MINUTES=$JWT_TTL_IN_MINUTES" >> .env

      - name: Cache cargo registry
        uses: actions/cache@v2
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-

      - name: Cache cargo build
        uses: actions/cache@v2
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-build-

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Copy .env file to Docker context
        run: cp .env .

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/example:latest